"""
Working paper: generate the hand-calibrated LaTeX tables that draftPaper.tex
\\input{}s. Mirrors makeMultipliers.py (which produces multipliersTable.tex from
the model output); this script produces the three tables whose contents are
calibration choices or notation rather than model output:

  parametersTable.tex     -> Table 1  (tab:parameters)   Selected Model Parameters
  efficiencyGapsTable.tex  -> Table 2  (tab:efficiencyGaps) Derivation of the gaps
  notationTable.tex        -> Table 4  (tab:notation)      Main Endogenous Variables

Each file holds only the `tabular` environment; the surrounding table float,
caption, label, source and note stay in draftPaper.tex (same split as
multipliersTable.tex). The values are encoded here, not recomputed, so the
compiled paper is unchanged when this runs.

Note on Table 2: the efficiency gaps are the 2023 income-group medians of
`eff_gap` from the IMF staff efficiency database (the same source as
fig:efficiencyBands; see plotEfficiencyBands.py). They are encoded here rather
than recomputed live: the current database snapshot yields values that differ by
~0.001 in a few cells (rounding/data-vintage drift), and the human-capital EMDE
average (0.329) is the mean of the four underlying sub-medians, not the mean of
the two rounded sector averages. Encoding keeps the published numbers stable.

Writes (next to multipliersTable.tex, \\input by draftPaper.tex):
  ../parametersTable.tex
  ../efficiencyGapsTable.tex
  ../notationTable.tex
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT_DIR = HERE.parent                              # docs/2026-06_wp-imf/

HEADER = ("% Generated by pyScripts/2026-06_wp-imf/makeTables.py "
          "(run via the docs copy). Do not edit by hand.")


def write_tex(name, lines):
    path = OUT_DIR / name
    path.write_text(HEADER + "\n" + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"  Wrote {path.name}")


# =============================================================================
# Table 1 - Selected Model Parameters
# =============================================================================
# (symbol, description, AE value, EMDE value); "--" where a channel is off.
PARAMETERS = [
    (r"$\alpha_G$",              "Output elasticity, infrastructure",       "0.05",  "0.17"),
    (r"$\alpha_{HA}$",           "Human capital elasticity, innovation",    "0.45",  "--"),
    (r"$\alpha_{RD}$",           r"Public R\&D elasticity, innovation",     "0.10",  "--"),
    (r"$\rho_A$",                "AR(1) coefficient, technology stock",     "0.79",  "0.79"),
    (r"$\phi$",                  "Survival rate of adopted technologies",   "0.97",  "0.97"),
    (r"$e^{GI}$",                "Inefficiency, infrastructure investment", "0.35",  "0.42"),
    (r"$e^{GE}$",                "Inefficiency, human capital investment",  "0.30",  "0.32"),
    (r"$e^{GRD}$",               r"Inefficiency, public R\&D spending",     "0.41",  "--"),
    (r"$\varsigma$",             "Elasticity, adoption probability",        "0.80",  "0.80"),
    (r"$q_0$",                   "Scale, adoption probability",             "0.10",  "0.10"),
    (r"$\delta^{GI},\delta^{GE}$", "Depreciation, public capital",          "0.025", "0.025"),
    (r"$\mu$",                   "Human capital elasticity, public stock",  "0.10",  "0.25"),
    (r"$\gamma$",                "Human capital elasticity, time input",    "0.50",  "0.50"),
]


def make_parameters():
    lines = [
        r"\begin{tabular}{llcc}",
        r"    \toprule",
        r"    & Description & AE & EMDE \\",
        r"    \midrule",
    ]
    for sym, desc, ae, emde in PARAMETERS:
        lines.append(f"    {sym} & {desc} & {ae} & {emde} \\\\")
    lines += [r"    \bottomrule", r"\end{tabular}"]
    write_tex("parametersTable.tex", lines)


# =============================================================================
# Table 2 - Derivation of the Spending-Efficiency Gaps
# =============================================================================
# Each row: (label, AE cell, EMDE cell). The EMDE sector cells show the
# (emerging-market + low-income)/2 averaging explicitly; the summary rows give
# the result directly. Values are 2023 medians of eff_gap (see module docstring).
EFFICIENCY_ROWS = [
    ("row",  "Infrastructure",          "0.359", r"$(0.371+0.441)/2 = 0.406$"),
    ("gap",),
    ("row",  r"\quad Health",           "0.295", r"$(0.311+0.307)/2 = 0.309$"),
    ("row",  r"\quad Education",        "0.318", r"$(0.347+0.350)/2 = 0.348$"),
    ("gap",),
    ("row",  "Human capital (average)", "0.306", "0.329"),
    ("gap",),
    ("row",  r"R\&D",                   "0.399", "--"),
]


def make_efficiency_gaps():
    lines = [
        r"\begin{tabular}{lcc}",
        r"    \toprule",
        r"    Efficiency gap ($1-$ efficiency) & AE & EMDE \\",
        r"    \midrule",
    ]
    for row in EFFICIENCY_ROWS:
        if row[0] == "gap":
            lines.append(r"    \addlinespace[0.3em]")
        else:
            _, label, ae, emde = row
            lines.append(f"    {label} & {ae} & {emde} \\\\")
    lines += [r"    \bottomrule", r"\end{tabular}"]
    write_tex("efficiencyGapsTable.tex", lines)


# =============================================================================
# Table 4 - Main Endogenous Variables (two symbol/description column pairs)
# =============================================================================
NOTATION = [
    (r"$C_t$",        "Consumption",               r"$A_t$",          "Adopted technologies"),
    (r"$L_t$",        "Labor supply",              r"$Z_t$",          "Created technologies"),
    (r"$E_t$",        "Time in human capital",     r"$S_t$",          "Adoption expenditure"),
    (r"$N_t$",        r"Effective labor $H_t L_t$", r"$q_t$",         "Adoption probability"),
    (r"$H_t$",        "Private human capital",     r"$\mathcal{V}_t$", "Value of adopted tech."),
    (r"$I_t$",        "Private investment",        r"$\mathcal{J}_t$", "Value of unadopted tech."),
    (r"$K_t$",        "Private capital",           r"$G_t^{C}$",      "Government consumption"),
    (r"$w_t$",        "Real wage",                 r"$I_t^{GI}$",     "Public infrastructure inv."),
    (r"$r_t^{k}$",    "Rental rate of capital",    r"$I_t^{GE}$",     "Public human capital inv."),
    (r"$\lambda_t$",  "Marginal utility",          r"$G_t^{RD}$",     r"Public R\&D spending"),
    (r"$\lambda_t^{H}$", "Shadow value of $H_t$",  r"$K_t^{GI}$",     "Public infrastructure capital"),
    (r"$Y_t^{d}$",    "Aggregate demand",          r"$K_t^{GE}$",     "Public human capital"),
    (r"$Y_t$",        "Gross output",              r"$D_t$",          "Public debt"),
    (r"$mc_t$",       "Real marginal cost",        r"$d_t$",          "Debt-to-GDP ratio"),
    (r"$\Pi_t$",      "Gross inflation",           r"$T_t$",          "Lump-sum transfers"),
    (r"$\Pi_t^{*}$",  "Reset inflation",           r"$\tau_t^{c},\tau_t^{w}$", "Consumption, labor tax"),
    (r"$v_t^{p}$",    "Price dispersion",          r"$R_t^{mp}$",     "Policy rate"),
    (r"$\Lambda_t$",  "Balanced-growth trend",     r"$R_t$",          "Government borrowing rate"),
]


def make_notation():
    lines = [
        r"\begin{tabular}{ll@{\qquad}ll}",
        r"    \toprule",
        r"    Symbol & Description & Symbol & Description \\",
        r"    \midrule",
    ]
    for s1, d1, s2, d2 in NOTATION:
        lines.append(f"    {s1} & {d1} & {s2} & {d2} \\\\")
    lines += [r"    \bottomrule", r"\end{tabular}"]
    write_tex("notationTable.tex", lines)


def main():
    make_parameters()
    make_efficiency_gaps()
    make_notation()


if __name__ == "__main__":
    main()
