"""
Working paper: generate the symbol glossary in the appendix (app:glossary) —
three `longtable`s mapping paper notation to the model-code names, with a short
description: endogenous variables, parameters, and exogenous variables (shocks).

The tables are COMPLETE: they list every `var`/`parameters`/`varexo` name declared
in models/declare_all.macro (counts must match the model). Rows are grouped by the
Section 2 structure of the paper (Households; Production and technology; Government:
fiscal and monetary policy; Market clearing and equilibrium; Balanced growth), with
an Auxiliary/steady-state/reporting group at the end for objects that are not part
of that narrative. The model-code column is the authoritative anchor; the Paper
column shows the paper symbol, or "--" when there is none.

Writes (\\input by draftPaper.tex):
  ../glossaryEndogenous.tex
  ../glossaryParameters.tex
  ../glossaryExogenous.tex
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT_DIR = HERE.parent                                # docs/2026-06_wp-imf/

HEADER = ("% Generated by pyScripts/2026-06_wp-imf/makeGlossary.py "
          "(run via the docs copy). Do not edit by hand.")

# Each table is a list of (group title, [ (paper symbol, description, model code), ... ]).
# Numbering is continuous across groups (so the last number is the total count).

ENDOGENOUS = [
    ("Households", [
        (r"$C_t$",            "Consumption",                              "C"),
        (r"$L_t$",            "Labor supply (hours)",                     "L"),
        (r"$N_t$",            r"Effective labor, $H_{t-1} L_t$",          "N"),
        (r"$H_t$",            "Private human-capital stock",              "H"),
        (r"$E_t$",            "Time in human-capital accumulation",       "E"),
        (r"$I_t$",            "Private investment",                       "Ip"),
        (r"$K_t$",            "Private capital",                          "Kp"),
        (r"$r_t^{k}$",        "Rental rate of private capital",           "rk"),
        (r"$w_t$",            "Real wage",                                "w"),
        (r"$\lambda_t$",      "Marginal utility of consumption",          "lambda"),
        (r"$\lambda_t^{H}$",  "Shadow value of human capital",            "lambda_H"),
        (r"$\mathit{SDF}_t$", "Stochastic discount factor",               "SDF"),
        (r"$\omega$",         "Labor-disutility scaling",                 "omega"),
        (r"$\chi$",           r"Scale in human-capital accumulation",     "chiH"),
    ]),
    ("Production and technology", [
        (r"$Y_t$",            "Gross output",                             "y"),
        (r"$mc_t$",           "Real marginal cost",                       "mc"),
        (r"$\Pi_t$",          "Gross inflation",                          "PI"),
        (r"$\Pi_t^{*}$",      "Reset (optimal) inflation",                "PIstar"),
        (r"$x_{1,t}$",        "Price-setting auxiliary",                  "x1"),
        (r"$x_{2,t}$",        "Price-setting auxiliary",                  "x2"),
        (r"$A_t$",            "Adopted technology",                       "A"),
        (r"$Z_t$",            "Created technology",                       "Z"),
        (r"$S_t$",            "Adoption expenditure",                     "S"),
        (r"$q_t$",            "Adoption probability",                     "q"),
        (r"$\mathcal{V}_t$",  "Value of an adopted technology",           "V"),
        (r"$\mathcal{J}_t$",  "Value of an unadopted technology",         "J"),
        ("--",                r"R\&D-process productivity disturbance",   "shockchi"),
    ]),
    ("Government: fiscal and monetary policy", [
        (r"$G_t^{C}$",        "Government consumption",                   "Gc"),
        (r"$I_t^{GI}$",       "Public infrastructure investment",         "Igi"),
        (r"$K_t^{GI}$",       "Public infrastructure capital",            "Kg"),
        (r"$I_t^{GE}$",       "Public human-capital investment",          "Ige"),
        (r"$K_t^{GE}$",       "Public human-capital stock",               "Kge"),
        (r"$G_t^{RD}$",       r"Public R\&D spending",                    "Grd"),
        (r"$G_t$",            "Total government spending",                "G"),
        (r"$D_t$",            "Public debt",                              "b"),
        (r"$d_t$",            "Debt-to-GDP ratio",                        "by"),
        (r"$T_t$",            "Lump-sum transfers",                       "T"),
        (r"$\tau_t^{c}$",     "Consumption-tax rate",                     "tauc"),
        (r"$\tau_t^{w}$",     "Labor-income-tax rate",                    "tauw"),
        (r"$R_t^{mp}$",       "Monetary-policy rate",                     "Rmp"),
        (r"$R_t$",            "Government borrowing rate",                "R"),
        ("--",                "Expected default loss",                    "Delta_G"),
        ("--",                "Probability of default",                   "prob_def"),
        (r"$e_t^{GI}$",       "Infrastructure efficiency gap",            "eGI"),
        (r"$e_t^{GE}$",       "Human-capital efficiency gap",             "eGE"),
        (r"$e_t^{GRD}$",      r"R\&D efficiency gap",                     "eGRD"),
    ]),
    ("Market clearing and equilibrium", [
        (r"$Y_t^{d}$",        "Aggregate demand",                         "yd"),
        (r"$v_t^{p}$",        "Price dispersion",                         "vp"),
    ]),
    ("Balanced growth", [
        (r"$g_t$",            "Gross growth rate",                        "g"),
    ]),
    ("Auxiliary, steady-state, and reporting", [
        (r"$R_t/\Pi_t$",      "Ex-post real interest rate",               "rreal"),
        (r"$TFP_t$",          "Total factor productivity",                "TFP"),
        ("--",                "Adoption-probability scale (steady state)", "kappaprob"),
        ("--",                "Output growth rate",                       "ygrowth"),
        ("--",                "Primary deficit",                          "pdef"),
        ("--",                "Steady-state output (value added)",        "ydss"),
        ("--",                "Steady-state borrowing rate",              "Rss"),
        ("--",                "Steady-state government consumption",       "Gcss"),
        ("--",                "Steady-state infrastructure investment",   "Igiss"),
        ("--",                "Steady-state human-capital investment",    "Igess"),
        ("--",                r"Steady-state R\&D spending",              "Grdss"),
        ("--",                r"Steady-state R\&D-process disturbance",   "shockchiss"),
        ("--",                "Log of aggregate demand",                  "lnyd"),
        ("--",                "Log of the price index",                   "lnPI"),
        ("--",                r"Log of R\&D spending",                    "ln_Grd"),
        ("--",                "Debt-to-GDP, annualized",                  "by_ann"),
        ("--",                "Infrastructure investment, share of GDP",  "Igi_ys"),
        ("--",                "Primary deficit, share of steady-state GDP", "pdef_yss"),
        ("--",                "Transfers, share of steady-state GDP",     "T_yss"),
        ("--",                "Debt service, share of steady-state GDP",  "dserv_yss"),
        ("--",                "Public debt, share of steady-state GDP",   "by_yss"),
        ("--",                r"R\&D spending, share of steady-state GDP", "Grd_ydss_ratio"),
    ]),
]

PARAMETERS = [
    ("Households", [
        (r"$\beta$",            "Discount factor",                              "betta"),
        (r"$\varphi$",          "Inverse Frisch elasticity",                    "varphi"),
        (r"$\delta$",           "Depreciation rate of capital (private and public)", "delta"),
        (r"$\delta^h$",         "Human-capital depreciation",                   "deltaH"),
        (r"$\gamma$",           "Human-capital elasticity, time input",         "gamma"),
        (r"$\mu$",              "Human-capital elasticity, public stock",       "mu"),
    ]),
    ("Production and technology", [
        (r"$\alpha$",           "Private capital share",                        "alpha"),
        (r"$\alpha_G$",         "Output elasticity of public infrastructure",   "alphaG"),
        (r"$\Theta$",           "Fixed cost of production",                     "Bigtheta"),
        ("--",                  "Fixed cost, share of GDP",                     "Bigtheta_y"),
        (r"$\theta_p$",         "Calvo non-reset probability",                  "thetap"),
        (r"$\chi_p$",           "Price indexation",                             "chi"),
        (r"$\epsilon$",         "Elasticity of substitution (sets the markup)", "epsilon"),
        (r"$\vartheta$",        "Love-of-variety / TFP exponent",               "vartheta"),
        ("--",                  "Steady-state gross markup",                    "markupss"),
        (r"$\rho_A$",           "Persistence of created technology",            "rho_A"),
        (r"$\alpha_{HA}$",      "Human-capital loading in tech creation",       "alphaHA"),
        (r"$\alpha_{RD}$",      "Public-R\\&D loading in tech creation",        "alphaRD"),
        (r"$\phi$",             "Survival rate of adopted technologies",        "phi"),
        (r"$\varsigma$",        "Adoption-probability elasticity",              "varsigma"),
        ("--",                  "Steady-state adoption probability",            "qss"),
        ("--",                  "R\\&D-process shock persistence",              "rhoshockchi"),
    ]),
    ("Government: fiscal and monetary policy", [
        (r"$\Pi$",              "Steady-state gross inflation",                 "Piss"),
        (r"$\rho_R$",           "Policy-rate smoothing",                        "rho_R"),
        (r"$\gamma_\pi$",       "Policy response to inflation",                 "gamma_pi"),
        (r"$\gamma_y$",         "Policy response to the output gap",            "gamma_y"),
        (r"$\rho_{RG}$",        "Government-bond-rate persistence (maturity)",   "rho_RG"),
        (r"$\Delta$",           "Debt feedback on the borrowing rate",          "Deltacost"),
        (r"$\eta_1$",           "Sovereign-default parameter 1",                "eta1"),
        (r"$\eta_2$",           "Sovereign-default parameter 2",                "eta2"),
        (r"$\rho_{\tau c}$",    "Consumption-tax persistence",                  "rho_tauc"),
        (r"$\tau^c$",           "Steady-state consumption-tax rate",            "taucss"),
        (r"$\gamma^{\tau c}_d$","Consumption-tax response to debt",             "gamma_d_tauc"),
        (r"$\rho_{\tau w}$",    "Labor-tax persistence",                        "rho_tauw"),
        (r"$\tau^w$",           "Steady-state labor-tax rate",                  "tauwss"),
        (r"$\gamma^{\tau w}_d$","Labor-tax response to debt",                   "gamma_d_tauw"),
        (r"$d^*$",              "Steady-state debt-to-GDP ratio",               "byss"),
        (r"$\gamma^{T}_d$",     "Transfer response to debt",                    "gamma_d_trans"),
        (r"$\rho_T$",           "Transfer persistence",                         "rho_trans"),
        ("--",                  "Infrastructure investment, share of GDP",      "Igiy"),
        ("--",                  "Government consumption, share of GDP",          "Gcy"),
        ("--",                  "Human-capital investment, share of GDP",       "Igey"),
        ("--",                  "R\\&D spending, share of GDP",                 "Grdy"),
        (r"$e^{GI}$",           "Steady-state infrastructure efficiency gap",   "eGI_ss"),
        (r"$e^{GE}$",           "Steady-state human-capital efficiency gap",    "eGE_ss"),
        (r"$e^{GRD}$",          "Steady-state R\\&D efficiency gap",            "eGRD_ss"),
    ]),
    ("Balanced growth", [
        (r"$g$",                "Steady-state gross growth",                    "gss"),
        ("--",                  "Trend-growth shock persistence",               "rho_g"),
        ("--",                  "Net trend growth of technology",               "gammaa"),
    ]),
]

EXOGENOUS = [
    ("Production and technology", [
        ("--",                          r"R\&D-process (productivity) shock",         "epsi_shockchi"),
        (r"$\varepsilon_t^{q}$",        "Adoption-probability shock",                 "epsirhoadopt"),
        (r"$\varepsilon_t^{\alpha gi}$","Infrastructure-elasticity (allocative) shock", "epsiallo_ig"),
        (r"$\varepsilon_t^{\alpha ge}$","Human-capital-elasticity (allocative) shock",  "epsiallo_ige"),
    ]),
    ("Government: fiscal and monetary policy", [
        (r"$\varepsilon_t^{c}$",        "Government-consumption shock",                "epsi_gc"),
        (r"$\varepsilon_t^{gi}$",       "Infrastructure-investment shock",            "epsi_igi"),
        (r"$\varepsilon_t^{ge}$",       "Human-capital-investment shock",             "epsi_ige"),
        (r"$\varepsilon_t^{rd}$",       r"R\&D-spending shock",                       "epsi_grd"),
        (r"$\varepsilon_t^{mp}$",       "Monetary-policy shock",                      "epsi_MP"),
        (r"$\varepsilon_t^{spr}$",      "Sovereign-spread shock",                     "epsi_spread"),
        (r"$\varepsilon_t^{\tau c}$",   "Consumption-tax shock",                      "epsi_tauc"),
        (r"$\varepsilon_t^{\tau w}$",   "Labor-tax shock",                            "epsi_tauw"),
        (r"$\varepsilon_t^{ge,\mathit{eff}}$", "Human-capital-efficiency shock",      "epsi_effge"),
        (r"$\varepsilon_t^{gi,\mathit{eff}}$", "Infrastructure-efficiency shock",     "epsi_eff"),
        (r"$\varepsilon_t^{rd,\mathit{eff}}$", r"R\&D-efficiency shock",              "epsi_effcgrd"),
    ]),
    ("Balanced growth", [
        (r"$\varepsilon_t^{g}$",        "Trend-growth shock",                         "epsi_g"),
    ]),
]


def longtable(groups, caption, label):
    head = r"\# & Paper & Description & Model code \\"
    lines = [
        HEADER,
        r"\begin{longtable}{@{}r@{\hskip 10pt}l >{\raggedright\arraybackslash}p{7.6cm} l@{}}",
        rf"\caption{{{caption}}}\label{{{label}}}\\",
        r"\toprule", head, r"\midrule", r"\endfirsthead",
        r"\multicolumn{4}{c}{{\tablename\ \thetable{} -- continued from previous page}}\\",
        r"\toprule", head, r"\midrule", r"\endhead",
        r"\midrule", r"\multicolumn{4}{r}{\textit{continued on next page}}\\", r"\endfoot",
        r"\bottomrule", r"\endlastfoot",
    ]
    n = 0
    for gi, (title, rows) in enumerate(groups):
        if gi > 0:
            lines.append(r"\addlinespace[0.4em]")
        lines.append(rf"\multicolumn{{4}}{{@{{}}l}}{{\textit{{{title}}}}} \\")
        lines.append(r"\addlinespace[0.1em]")
        for paper, desc, model in rows:
            n += 1
            code = model.replace("_", r"\_")
            lines.append(rf"{n} & {paper} & {desc} & \texttt{{{code}}} \\")
    lines.append(r"\end{longtable}")
    return "\n".join(lines) + "\n"


def main():
    specs = [
        (ENDOGENOUS, "Endogenous Variables", "tab:glossEndo", "glossaryEndogenous.tex"),
        (PARAMETERS, "Parameters",           "tab:glossParam", "glossaryParameters.tex"),
        (EXOGENOUS,  "Exogenous Variables (Shocks)", "tab:glossExo", "glossaryExogenous.tex"),
    ]
    for groups, caption, label, fname in specs:
        (OUT_DIR / fname).write_text(longtable(groups, caption, label), encoding="utf-8")
        nrows = sum(len(rows) for _, rows in groups)
        print(f"  Wrote {fname} ({nrows} rows)")


if __name__ == "__main__":
    main()
