"""
Working paper: generate Table 2 (tab:efficiencyGaps), "Derivation of the
Spending-Efficiency Gaps", directly from the spending-efficiency database.

Data-driven: this reads the same IMF staff efficiency estimates that
fig:efficiencyBands plots (plotEfficiencyBands.py) and recomputes the 2023
income-group medians of `eff_gap`, so the table and the appendix chart always
agree. Run it whenever the underlying database changes.

Construction (matches the table note):
  - AE column            = the advanced-economy 2023 median for the sector.
  - EMDE column, sectors = (emerging-market median + low-income median)/2, shown
                           explicitly as the averaging arithmetic.
  - Human capital row    = the average of the health and education gaps (per
                           column), computed at full precision.
  - R&D                  = advanced economies only; EMDE is shut down ("--").
Values are rounded to three decimals for display only.

Writes only the `tabular` environment to ../efficiencyGapsTable.tex; the
surrounding table float, caption, label, source and note stay in draftPaper.tex
(same split as multipliersTable.tex).
"""
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "efficiencyGapsTable.tex"      # docs/2026-06_wp-imf/

# IMF staff efficiency estimates (2025-04-14), [SECTOR]_inefficiency-scores.csv,
# eff_gap column. The Developer copy; the Documents copy is stale. Same source
# as plotEfficiencyBands.py (fig:efficiencyBands).
DATA_DIR = "/Users/kk/Developer/2025-05_fmEfficiencyScores/code-output/2025-04-14-efficiency-estimates"
REF_YEAR = 2023

HEADER = ("% Generated by pyScripts/2026-06_wp-imf/makeEfficiencyGapsTable.py "
          "from the efficiency database. Do not edit by hand.")


def median(sector, income):
    """2023 median eff_gap for one sector file and income group."""
    df = pd.read_csv(f"{DATA_DIR}/{sector}_inefficiency-scores.csv",
                     usecols=["year", "income", "eff_gap"]).dropna(subset=["eff_gap"])
    d = df[(df["year"] == REF_YEAR) & (df["income"] == income)]
    return float(d["eff_gap"].median())


def f3(x):
    """Round to three decimals, half-up, for display."""
    return str(Decimal(x).quantize(Decimal("0.001"), rounding=ROUND_HALF_UP))


def emde_cell(em, lic):
    """EMDE sector cell: the (EM + LIC)/2 averaging shown explicitly."""
    return f"$({f3(em)}+{f3(lic)})/2 = {f3((em + lic) / 2)}$"


def main():
    # Sector medians by income group.
    inf = {g: median("INF", g) for g in ("AE", "EM", "LIC")}
    hlt = {g: median("HLT", g) for g in ("AE", "EM", "LIC")}
    edu = {g: median("EDU", g) for g in ("AE", "EM", "LIC")}
    rnd_ae = median("RND", "AE")

    # Human capital = average of health and education, per column (full precision).
    hc_ae = (hlt["AE"] + edu["AE"]) / 2
    hc_emde = (hlt["EM"] + hlt["LIC"] + edu["EM"] + edu["LIC"]) / 4

    rows = [
        ("row",  "Infrastructure",          f3(inf["AE"]), emde_cell(inf["EM"], inf["LIC"])),
        ("gap",),
        ("row",  r"\quad Health",           f3(hlt["AE"]), emde_cell(hlt["EM"], hlt["LIC"])),
        ("row",  r"\quad Education",        f3(edu["AE"]), emde_cell(edu["EM"], edu["LIC"])),
        ("gap",),
        ("row",  "Human capital (average)", f3(hc_ae),     f3(hc_emde)),
        ("gap",),
        ("row",  r"R\&D",                   f3(rnd_ae),    "--"),
    ]

    lines = [
        HEADER,
        r"\begin{tabular}{lcc}",
        r"    \toprule",
        r"    Efficiency gap ($1-$ efficiency) & AE & EMDE \\",
        r"    \midrule",
    ]
    for row in rows:
        if row[0] == "gap":
            lines.append(r"    \addlinespace[0.3em]")
        else:
            _, label, ae, emde = row
            lines.append(f"    {label} & {ae} & {emde} \\\\")
    lines += [r"    \bottomrule", r"\end{tabular}"]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  Wrote {OUT.name}")


if __name__ == "__main__":
    main()
