"""
Generate the AE and EMDE steady-state target table for the working paper.

Values are read from the committed result files and converted to reader-facing
annual or percentage units. In particular, the model's debt ratio uses quarterly
GDP as its denominator, so it is divided by four for reporting against annual GDP.

Writes:
  ../calibrationTargetsTable.tex
"""
from pathlib import Path

from scipy.io import loadmat

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "calibrationTargetsTable.tex"
REPO = HERE.parents[2]
MODELS = REPO / "models"
AE_MODEL = "Model_HumanCapital_exp_gc"
EM_MODEL = "EM_Model_HumanCapital_exp_gc"

HEADER = ("% Generated by pyScripts/2026-06_wp-imf/"
          "makeCalibrationTargetsTable.py. Do not edit by hand.")


def read_params(model):
    m = loadmat(MODELS / model / "Output" / f"{model}_results.mat")["M_"]
    names = [str(x[0]) for x in m["param_names"][0, 0][:, 0]]
    return dict(zip(names, m["params"][0, 0].ravel()))


def pct(value, decimals=1):
    return f"{100 * float(value):.{decimals}f}"


def annual_growth(value):
    return f"{100 * (float(value) ** 4 - 1):.1f}"


def main():
    ae = read_params(AE_MODEL)
    em = read_params(EM_MODEL)

    rows = [
        ("Growth", None, None, None, None),
        (r"$g^4-1$", "Annual trend output growth", "Percent", annual_growth(ae["g"]), annual_growth(em["g"])),
        ("Public spending", None, None, None, None),
        (r"$\hat G^{C,SS}/\hat Y^{d,SS}$", "Government consumption", "Percent of GDP", pct(ae["Gcy"]), pct(em["Gcy"])),
        (r"$\hat I^{GI,SS}/\hat Y^{d,SS}$", "Infrastructure investment", "Percent of GDP", pct(ae["Igiy"]), pct(em["Igiy"])),
        (r"$\hat I^{GE,SS}/\hat Y^{d,SS}$", "Human-capital investment", "Percent of GDP", pct(ae["Igey"]), pct(em["Igey"])),
        (r"$\hat G^{RD,SS}/\hat Y^{d,SS}$", r"Public R\&D spending", "Percent of GDP", pct(ae["Grdy"]), pct(em["Grdy"])),
        ("Implicit tax rates", None, None, None, None),
        (r"$\tau^{c,SS}$", "Consumption tax", "Percent", pct(ae["taucss"]), pct(em["taucss"])),
        (r"$\tau^{w,SS}$", "Labor-income tax", "Percent", pct(ae["tauwss"]), pct(em["tauwss"])),
        ("Public debt", None, None, None, None),
        (r"$\hat B^{SS}/(4\hat Y^{d,SS})$", "Public debt level", "Percent of annual GDP", pct(ae["byss"] / 4), pct(em["byss"] / 4)),
    ]

    lines = [
        HEADER,
        r"\begin{tabular}{lllcc}",
        r"    \toprule",
        r"    Symbol & Target & Unit & AE & EMDE \\",
        r"    \midrule",
    ]
    first_group = True
    for symbol, label, unit, ae_value, em_value in rows:
        if unit is None:
            if not first_group:
                lines.append(r"    \addlinespace[0.4em]")
            lines.append(rf"    \multicolumn{{5}}{{@{{}}l}}{{\textit{{{symbol}}}}} \\")
            lines.append(r"    \addlinespace[0.1em]")
            first_group = False
        else:
            lines.append(rf"    \quad {symbol} & {label} & {unit} & {ae_value} & {em_value} \\")
    lines += [r"    \bottomrule", r"\end{tabular}"]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  Wrote {OUT.name}")


if __name__ == "__main__":
    main()
