"""
Working paper: generate Table 2 (tab:efficiencyGaps), "Derivation of the
Spending-Efficiency Gaps".

Writes only the `tabular` environment to ../efficiencyGapsTable.tex; the
surrounding table float, caption, label, source and note stay in draftPaper.tex
(same split as multipliersTable.tex).

The gaps are the 2023 income-group medians of `eff_gap` from the IMF staff
efficiency database (the same source as fig:efficiencyBands; see
plotEfficiencyBands.py). They are encoded here rather than recomputed live: the
current database snapshot yields values that differ by ~0.001 in a few cells
(rounding/data-vintage drift), and the human-capital EMDE average (0.329) is the
mean of the four underlying sub-medians, not the mean of the two rounded sector
averages. Encoding keeps the published numbers stable.

Writes (\\input by draftPaper.tex):
  ../efficiencyGapsTable.tex
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "efficiencyGapsTable.tex"      # docs/2026-06_wp-imf/

HEADER = ("% Generated by pyScripts/2026-06_wp-imf/makeEfficiencyGapsTable.py "
          "(run via the docs copy). Do not edit by hand.")

# Each row: ("row", label, AE cell, EMDE cell) or ("gap",) for \addlinespace.
# The EMDE sector cells show the (emerging-market + low-income)/2 averaging
# explicitly; the summary rows give the result directly.
ROWS = [
    ("row",  "Infrastructure",          "0.359", r"$(0.371+0.441)/2 = 0.406$"),
    ("gap",),
    ("row",  r"\quad Health",           "0.295", r"$(0.311+0.307)/2 = 0.309$"),
    ("row",  r"\quad Education",        "0.318", r"$(0.347+0.350)/2 = 0.348$"),
    ("gap",),
    ("row",  "Human capital (average)", "0.306", "0.329"),
    ("gap",),
    ("row",  r"R\&D",                   "0.399", "--"),
]


def main():
    lines = [
        HEADER,
        r"\begin{tabular}{lcc}",
        r"    \toprule",
        r"    Efficiency gap ($1-$ efficiency) & AE & EMDE \\",
        r"    \midrule",
    ]
    for row in ROWS:
        if row[0] == "gap":
            lines.append(r"    \addlinespace[0.3em]")
        else:
            _, label, ae, emde = row
            lines.append(f"    {label} & {ae} & {emde} \\\\")
    lines += [r"    \bottomrule", r"\end{tabular}"]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  Wrote {OUT.name}")


if __name__ == "__main__":
    main()
