"""
Working paper: generate the symbol glossary in the appendix (app:glossary) —
three `longtable`s mapping paper notation to the model-code names, with a short
description: endogenous variables, parameters, and exogenous variables (shocks).

The tables are COMPLETE: they list every `var`/`parameters`/`varexo` name declared
in models/declare_all.macro (counts must match the model). Rows are grouped by the
Section 2 structure of the paper (Households; Production and technology; Government:
fiscal and monetary policy; Market clearing and equilibrium; Balanced growth), with
an Auxiliary/steady-state/reporting group at the end for objects that are not part
of that narrative. The model-code column is the authoritative anchor; the Paper
column shows the paper symbol, or "--" when there is none.

Writes (\\input by draftPaper.tex):
  ../glossaryEndogenous.tex
  ../glossaryParameters.tex
  ../glossaryExogenous.tex
"""
from pathlib import Path

from scipy.io import loadmat

HERE = Path(__file__).resolve().parent
OUT_DIR = HERE.parent                                # docs/2026-06_wp-imf/
REPO = HERE.parents[2]                               # repo root
MODELS_DIR = REPO / "models"
AE_MODEL = "Model_HumanCapital_exp_gc"
EM_MODEL = "EM_Model_HumanCapital_exp_gc"

HEADER = ("% Generated by pyScripts/2026-06_wp-imf/makeGlossary.py "
          "(run via the docs copy). Do not edit by hand.")

# Technology-creation parameters that are inactive for EMDEs and shown "--" in
# the EMDE value column. Adoption remains active with the calibrated varsigma.
EMDE_DASH = {"rho_A", "alphaHA", "alphaRD", "eGRD_ss"}


def read_params(model):
    """Return {param_name: value} from the committed <model>_results.mat."""
    M = loadmat(MODELS_DIR / model / "Output" / f"{model}_results.mat")["M_"]
    names = [str(x[0]) for x in M["param_names"][0, 0][:, 0]]
    return dict(zip(names, M["params"][0, 0].ravel()))


def read_steady(model):
    """Return {endo_name: steady-state value} from the committed <model>_results.mat."""
    m = loadmat(MODELS_DIR / model / "Output" / f"{model}_results.mat")
    names = [str(x[0]) for x in m["M_"]["endo_names"][0, 0][:, 0]]
    return dict(zip(names, m["oo_"]["steady_state"][0, 0].ravel()))


def fmt_val(x):
    """Format at up to 3 decimal places (trailing zeros trimmed); fall back to
    significant figures only when 3 dp would round the value to zero."""
    x = float(x)
    if abs(x) < 1e-12:
        return "0"
    s = f"{x:.3f}"
    if float(s) == 0:            # too small for 3 dp -> keep significant figures
        s = f"{x:.3g}"
    return s.rstrip("0").rstrip(".") if "." in s else s

# Each table is a list of (group title, [ (paper symbol, description, model code), ... ]).
# Numbering is continuous across groups (so the last number is the total count).

ENDOGENOUS = [
    ("Households", [
        (r"$C_t$",            "Consumption",                              "C"),
        (r"$L_t$",            "Labor supply (hours)",                     "L"),
        (r"$N_t$",            r"Effective labor, $H_{t-1} L_t$",          "N"),
        (r"$H_t$",            "Private human-capital stock",              "H"),
        (r"$E_t$",            "Time in human-capital accumulation",       "E"),
        (r"$I_t$",            "Private investment",                       "Ip"),
        (r"$K_t$",            "Private capital",                          "Kp"),
        (r"$\lambda_t$",      "Marginal utility of consumption",          "lambda"),
        (r"$\lambda_t^{H}$",  "Shadow value of human capital",            "lambda_H"),
    ]),
    ("Production and technology: price setting", [
        (r"$x_{1,t}$",        "Price-setting auxiliary",                  "x1"),
        (r"$x_{2,t}$",        "Price-setting auxiliary",                  "x2"),
        (r"$\Pi_t^{*}$",      "Reset (optimal) inflation",                "PIstar"),
        (r"$\Pi_t$",          "Gross inflation",                          "PI"),
    ]),
    ("Production and technology: intermediate goods", [
        (r"$Y_t$",            "Gross output",                             "y"),
        (r"$mc_t$",           "Real marginal cost",                       "mc"),
        (r"$r_t^{k}$",        "Rental rate of private capital",           "rk"),
        (r"$w_t$",            "Real wage",                                "w"),
    ]),
    ("Production and technology: creation and adoption", [
        (r"$Z_t$",            "Created technology",                       "Z"),
        (r"$A_t$",            "Adopted technology",                       "A"),
        (r"$q_t$",            "Adoption probability",                     "q"),
        (r"$\mathit{SDF}_t$", "Stochastic discount factor",               "SDF"),
        (r"$\mathcal{V}_t$",  "Value of an adopted technology",           "V"),
        (r"$\mathcal{J}_t$",  "Value of an unadopted technology",         "J"),
        (r"$S_t$",            "Adoption expenditure",                     "S"),
    ]),
    ("Government: fiscal and monetary policy", [
        (r"$G_t^{C}$",        "Government consumption",                   "Gc"),
        (r"$I_t^{GI}$",       "Public infrastructure investment",         "Igi"),
        (r"$K_t^{GI}$",       "Public infrastructure capital",            "Kg"),
        (r"$I_t^{GE}$",       "Public education and health investment",   "Ige"),
        (r"$K_t^{GE}$",       "Public education and health capital",      "Kge"),
        (r"$G_t^{RD}$",       r"Public R\&D spending",                    "Grd"),
        (r"$G_t$",            "Total government spending",                "G"),
        (r"$B_t$",            "Public debt",                              "b"),
        (r"$b_t$",            "Debt-to-GDP ratio",                        "by"),
        (r"$T_t$",            "Lump-sum transfers",                       "T"),
        (r"$\tau_t^{c}$",     "Consumption-tax rate",                     "tauc"),
        (r"$\tau_t^{w}$",     "Labor-income-tax rate",                    "tauw"),
        (r"$R_t$",            "Nominal policy and government financing rate", "R"),
        (r"$e_t^{GI}$",       "Infrastructure efficiency gap",            "eGI"),
        (r"$e_t^{GE}$",       "Education and health efficiency gap",      "eGE"),
        (r"$e_t^{GRD}$",      r"R\&D efficiency gap",                     "eGRD"),
    ]),
    ("Market clearing and equilibrium", [
        (r"$Y_t^{d}$",        "Aggregate demand",                         "yd"),
        (r"$v_t^{p}$",        "Price dispersion",                         "vp"),
    ]),
    ("Auxiliary and steady state", [
        (r"$R_t/\Pi_t$",      "Ex-post real interest rate",               "rreal"),
        ("--",                "Steady-state output (value added)",        "ydss"),
        ("--",                "Steady-state nominal interest rate",       "Rss"),
    ]),
    ("Reporting (share of steady-state GDP)", [
        ("--",                "Primary deficit",                          "pdef_yss"),
        ("--",                "Transfers",                                "T_yss"),
        ("--",                "Public debt",                              "by_yss"),
    ]),
]

PARAMETERS = [
    ("Households", [
        (r"$\beta$",            "Discount factor",                              "betta"),
        (r"$\varphi$",          "Inverse Frisch elasticity",                    "varphi"),
        (r"$\omega$",           "Labor-disutility scaling",                     "omega"),
        (r"$\delta$",           "Depreciation rate of physical capital (private and public)", "delta"),
        (r"$\delta^h$",         "Depreciation rate of human capital",           "deltaH"),
        (r"$\gamma$",           "Human-capital elasticity, time input",         "gamma"),
        (r"$\mu$",              "Human-capital elasticity, public stock",       "mu"),
        (r"$\chi$",             r"Scale in human-capital accumulation",         "chiH"),
    ]),
    ("Production and technology", [
        (r"$\alpha$",           "Private capital share",                        "alpha"),
        (r"$\alpha_G$",         "Output elasticity of public infrastructure",   "alphaG"),
        (r"$\theta_p$",         "Calvo non-reset probability",                  "thetap"),
        (r"$\chi_p$",           "Price indexation",                             "chi"),
        (r"$\epsilon$",         "Elasticity of substitution (sets the markup)", "epsilon"),
        (r"$\vartheta$",        "Love-of-variety / TFP exponent",               "vartheta"),
        (r"$\mu^{p}$",          "Gross markup of intermediate producers",       "markupss"),
        (r"$\rho_A$",           "Persistence of created technology",            "rho_A"),
        (r"$\alpha_{HA}$",      "Long-run HC elasticity in tech creation",      "alphaHA"),
        (r"$\alpha_{RD}$",      "Long-run R\\&D elasticity in tech creation",   "alphaRD"),
        (r"$\phi$",             "Survival rate of adopted technologies",        "phi"),
        (r"$\varsigma$",        "Adoption-probability elasticity",              "varsigma"),
        (r"$q_0$",              "Adoption-probability scale",                   "kappaprob"),
        ("--",                  "Steady-state adoption probability",            "qss"),
    ]),
    ("Government: fiscal and monetary policy", [
        (r"$\Pi$",              "Steady-state gross inflation",                 "Piss"),
        (r"$\rho_R$",           "Policy-rate smoothing",                        "rho_R"),
        (r"$\gamma_\pi$",       "Policy response to inflation",                 "gamma_pi"),
        (r"$\gamma_y$",         "Policy response to the output gap",            "gamma_y"),
        (r"$\tau^c$",           "Steady-state consumption-tax rate",            "taucss"),
        (r"$\tau^w$",           "Steady-state labor-tax rate",                  "tauwss"),
        (r"$b^*$",              "Steady-state debt-to-GDP ratio",               "byss"),
        (r"$\gamma^{T}_d$",     "Transfer response to debt",                    "gamma_d_T"),
        ("--",                  "Government consumption, share of GDP",          "Gcy"),
        ("--",                  "Infrastructure investment, share of GDP",      "Igiy"),
        ("--",                  "Human-capital investment, share of GDP",       "Igey"),
        ("--",                  "R\\&D spending, share of GDP",                 "Grdy"),
        (r"$e^{GI}$",           "Steady-state infrastructure efficiency gap",   "eGI_ss"),
        (r"$e^{GE}$",           "Steady-state human-capital efficiency gap",    "eGE_ss"),
        (r"$e^{GRD}$",          "Steady-state R\\&D efficiency gap",            "eGRD_ss"),
    ]),
    ("Balanced growth", [
        (r"$g$",                "Constant gross trend growth rate",              "g"),
        (r"$\gamma^{a}$",         "Net trend growth of technology",               "gammaa"),
    ]),
]

EXOGENOUS = [
    ("Production and technology", [
        (r"$\varepsilon_t^{q}$",        "Adoption-probability shock",                 "epsi_q"),
    ]),
    ("Government: fiscal and monetary policy", [
        (r"$\varepsilon_t^{c}$",        "Government-consumption shock",                "epsi_gc"),
        (r"$\varepsilon_t^{gi}$",       "Infrastructure-investment shock",            "epsi_igi"),
        (r"$\varepsilon_t^{ge}$",       "Human-capital-investment shock",             "epsi_ige"),
        (r"$\varepsilon_t^{rd}$",       r"R\&D-spending shock",                       "epsi_grd"),
        (r"$\varepsilon_t^{mp}$",       "Monetary-policy shock",                      "epsi_MP"),
        (r"$\varepsilon_t^{\tau c}$",   "Consumption-tax shock",                      "epsi_tauc"),
        (r"$\varepsilon_t^{\tau w}$",   "Labor-tax shock",                            "epsi_tauw"),
        (r"$e_{T,t}^{\mathrm{aux}}$",   "Auxiliary transfer-rule dummy",                 "eTaux"),
        (r"$\varepsilon_t^{gi,\mathit{eff}}$", "Infrastructure-efficiency shock",     "epsi_effgi"),
        (r"$\varepsilon_t^{ge,\mathit{eff}}$", "Human-capital-efficiency shock",      "epsi_effge"),
        (r"$\varepsilon_t^{rd,\mathit{eff}}$", r"R\&D-efficiency shock",              "epsi_effgrd"),
    ]),
]


# Defining/characteristic equation for each endogenous variable, in paper notation
# (stationarized model form; g is the gross trend growth rate). The pinned scale
# constants (omega, chiH, kappaprob) and pure steady-state values (ydss, Rss) carry no
# illuminating equation and are left without one.
EQNS = {
    # Households
    "C":        r"\tfrac{1}{C_t}=\lambda_t(1+\tau^c_t)",
    "L":        r"\omega(L_t+E_t)^{\varphi}=\lambda_t(1-\tau^w_t)w_t H_{t-1}",
    "N":        r"N_t=H_{t-1}L_t",
    "H":        r"H_t=(1-\delta^h)H_{t-1}+\chi E_t^{\gamma}(K^{GE}_{t-1})^{\mu}",
    "E":        r"\omega(L_t+E_t)^{\varphi}=\lambda^H_t\,\chi\gamma\,E_t^{\gamma-1}(K^{GE}_{t-1})^{\mu}",
    "Ip":       r"1=\beta\,\mathbb{E}_t\!\big[\tfrac{\lambda_{t+1}}{\lambda_t}(1-\delta+r^k_{t+1})/g\big]",
    "Kp":       r"g K_t=(1-\delta)K_{t-1}+I_t",
    "rk":       r"r^k_t=\alpha\,(mc_t/\mu^{p})\,Y_t/K_{t-1}",
    "w":        r"\tfrac{K_{t-1}}{N_t}=\tfrac{\alpha}{1-\alpha}\tfrac{w_t}{r^k_t}",
    "lambda":   r"\lambda_t=\beta\,\mathbb{E}_t\!\big[\lambda_{t+1}R_t/(g\Pi_{t+1})\big]",
    "lambda_H": r"\lambda^H_t=\beta\,\mathbb{E}_t\!\big[\lambda_{t+1}(1-\tau^w_{t+1})w_{t+1}L_{t+1}+\lambda^H_{t+1}(1-\delta^h)\big]",
    "SDF":      r"\mathit{SDF}_t=\beta\lambda_t(1+\tau^c_t)/[\lambda_{t-1}(1+\tau^c_{t-1})]",
    # Production and technology
    "y":        r"Y_t=A_{t-1}^{\vartheta-1}K_{t-1}^{\alpha}N_t^{1-\alpha}(K^{GI}_{t-1})^{\alpha_G}",
    "mc":       r"w_t=(1-\alpha)\,(mc_t/\mu^{p})\,Y_t/N_t",
    "PI":       r"1=\theta_p(\Pi_{t-1}^{\chi_p}/\Pi_t)^{1-\epsilon}+(1-\theta_p)(\Pi^*_t)^{1-\epsilon}",
    "PIstar":   r"\epsilon\,x_{1,t}=(\epsilon-1)\,x_{2,t}",
    "x1":       r"x_{1,t}=\lambda_t mc_t Y^d_t+\beta\theta_p\,\mathbb{E}_t(\Pi_t^{\chi_p}/\Pi_{t+1})^{-\epsilon}x_{1,t+1}",
    "x2":       r"x_{2,t}=\lambda_t\Pi^*_t Y^d_t+\beta\theta_p\,\mathbb{E}_t(\Pi_t^{\chi_p}/\Pi_{t+1})^{1-\epsilon}\tfrac{\Pi^*_t}{\Pi^*_{t+1}}x_{2,t+1}",
    "A":        r"(1+\gamma^{a}) A_t=q_t\phi(Z_{t-1}-A_{t-1})+\phi A_{t-1}",
    "Z":        r"\log\tfrac{Z_t}{Z^{SS}}=\rho_A\log\tfrac{Z_{t-1}}{Z^{SS}}+(1-\rho_A)\alpha_{HA}\log\tfrac{H_{t-1}}{H^{SS}}+(1-\rho_A)\alpha_{RD}\log\tfrac{(1-e^{GRD}_{t-1})G^{RD}_{t-1}}{(1-e^{GRD})G^{RD,SS}}",
    "S":        r"S_t=\varsigma q_t\phi\,\mathbb{E}_t\!\big[\mathit{SDF}_{t+1}\tfrac{1}{1+\gamma^{a}}\tfrac{A_{t-1}}{A_t}(\mathcal{V}_{t+1}-\mathcal{J}_{t+1})\big]",
    "q":        r"q_t=(q_0+\varepsilon^{q}_t)(S_t)^{\varsigma}",
    "V":        r"\mathcal{V}_t=\tfrac{\mu^p-1}{\mu^p}mc_t Y_t+\phi\,\mathbb{E}_t\big[\mathit{SDF}_{t+1}\mathcal{V}_{t+1}\tfrac{A_{t-1}}{A_t}\tfrac{1}{1+\gamma^{a}}\big]",
    "J":        r"\mathcal{J}_t=-S_t+\phi\,\mathbb{E}_t\big[\mathit{SDF}_{t+1}\tfrac{A_{t-1}}{A_t}\tfrac{1}{1+\gamma^{a}}(q_t\mathcal{V}_{t+1}+(1-q_t)\mathcal{J}_{t+1})\big]",
    # Government
    "Gc":       r"G^C_t=G^{C,SS}+Y^{d,SS}\varepsilon^{c}_t",
    "Igi":      r"I^{GI}_t=I^{GI,SS}+Y^{d,SS}\varepsilon^{gi}_t",
    "Kg":       r"g K^{GI}_t=(1-\delta)K^{GI}_{t-1}+(1-e^{GI}_t)I^{GI}_t",
    "Ige":      r"I^{GE}_t=I^{GE,SS}+Y^{d,SS}\varepsilon^{ge}_t",
    "Kge":      r"g K^{GE}_t=(1-\delta)K^{GE}_{t-1}+(1-e^{GE}_t)I^{GE}_t",
    "Grd":      r"G^{RD}_t=G^{RD,SS}+Y^{d,SS}\varepsilon^{rd}_t",
    "G":        r"G_t=G^C_t+I^{GI}_t+I^{GE}_t+G^{RD}_t",
    "b":        r"B_t=\tfrac{R_{t-1}}{\Pi_t}\tfrac{B_{t-1}}{g}+G^C_t+I^{GI}_t+I^{GE}_t+G^{RD}_t+T_t-\tau^w_t w_t N_t-\tau^c_t C_t",
    "by":       r"b_t=B_t/Y_t",
    "T":        r"T_t=T^{SS}-\gamma^T_d e_{T,t}^{\mathrm{aux}}(b_{t-1}-b^*)Y^{d,SS}",
    "tauc":     r"\tau^c_t=\tau^c+\varepsilon^{\tau c}_t",
    "tauw":     r"\tau^w_t=\tau^w+\varepsilon^{\tau w}_t",
    "R":        r"\tfrac{R_t}{R^{SS}}=\big(\tfrac{R_{t-1}}{R^{SS}}\big)^{\rho_R}\big[(\tfrac{\Pi_t}{\Pi})^{\gamma_\pi}(\tfrac{Y^d_t}{Y^{d,SS}})^{\gamma_y}\big]^{1-\rho_R}e^{\varepsilon^{mp}_t}",
    "eGI":      r"e^{GI}_t=e^{GI}-\varepsilon^{gi,\mathit{eff}}_t",
    "eGE":      r"e^{GE}_t=e^{GE}-\varepsilon^{ge,\mathit{eff}}_t",
    "eGRD":     r"e^{GRD}_t=e^{GRD}-\varepsilon^{rd,\mathit{eff}}_t",
    # Market clearing and equilibrium
    "yd":       r"Y^d_t=C_t+I_t+G^C_t+I^{GI}_t+I^{GE}_t+G^{RD}_t+\big(\tfrac{Z_{t-1}}{A_{t-1}}-1\big)S_t",
    "vp":       r"v^p_t=\theta_p(\Pi_{t-1}^{\chi_p}/\Pi_t)^{-\epsilon}v^p_{t-1}+(1-\theta_p)(\Pi^*_t)^{-\epsilon}",
    # Auxiliary and reporting
    "rreal":    r"r^{\mathit{real}}_t=R_t/\Pi_t",
    "pdef_yss": r"(G^C_t+I^{GI}_t+I^{GE}_t+G^{RD}_t+T_t-\tau^w_t w_t N_t-\tau^c_t C_t)/Y^{d,SS}",
    "T_yss":    r"T_t/Y^{d,SS}",
    "by_yss":   r"B_t/Y^{d,SS}",
}


def longtable(groups, caption, label, values=None, eqns=None, notes=None):
    withval = values is not None
    if withval and eqns:      # endogenous: equations + steady-state value columns
        width = "7.7cm"
    elif withval:             # parameters: value columns only
        width = "5.8cm"
    elif eqns:                # equations only
        width = "9.3cm"
    else:                     # exogenous
        width = "7.6cm"
    if withval:
        colspec = (r"@{}r@{\hskip 8pt}l >{\raggedright\arraybackslash}p{" + width
                   + r"} l r@{\hskip 12pt}r@{}")
        head = r"\# & Paper & Description & Model code & AE & EMDE \\"
        ncol = 6
    else:
        colspec = (r"@{}r@{\hskip 10pt}l >{\raggedright\arraybackslash}p{" + width
                   + r"} l@{}")
        head = r"\# & Paper & Description & Model code \\"
        ncol = 4
    lines = [
        HEADER,
        rf"\begin{{longtable}}{{{colspec}}}",
        rf"\caption{{{caption}}}\label{{{label}}}\\",
        r"\toprule", head, r"\midrule", r"\endfirsthead",
        rf"\multicolumn{{{ncol}}}{{c}}{{{{\tablename\ \thetable{{}} -- continued from previous page}}}}\\",
        r"\toprule", head, r"\midrule", r"\endhead",
        r"\midrule", rf"\multicolumn{{{ncol}}}{{r}}{{\textit{{continued on next page}}}}\\", r"\endfoot",
        r"\bottomrule", r"\endlastfoot",
    ]
    n = 0
    for gi, (title, rows) in enumerate(groups):
        if gi > 0:
            lines.append(r"\addlinespace[0.4em]")
        lines.append(rf"\multicolumn{{{ncol}}}{{@{{}}l}}{{\textit{{{title}}}}} \\")
        lines.append(r"\addlinespace[0.1em]")
        for paper, desc, model in rows:
            n += 1
            code = model.replace("_", r"\_")
            d = desc
            if notes and model in notes:
                d = d + notes[model]
            if eqns and model in eqns:
                d = d + r" \gloseq{" + eqns[model] + "}"
            if withval:
                vt = values.get(model, ("", ""))
                ae, em = vt[0], vt[1]
                if len(vt) > 2 and vt[2]:  # shade cells that differ (parameters table)
                    ae = r"\cellcolor{diffcell} " + ae
                    em = r"\cellcolor{diffcell} " + em
                lines.append(rf"{n} & {paper} & {d} & \texttt{{{code}}} & {ae} & {em} \\")
            else:
                lines.append(rf"{n} & {paper} & {d} & \texttt{{{code}}} \\")
    lines.append(r"\end{longtable}")
    return "\n".join(lines) + "\n"


def main():
    # AE/EMDE steady-state values (endogenous variables) and calibrated parameters.
    aess, emss = read_steady(AE_MODEL), read_steady(EM_MODEL)
    # Parameter-table values: read from params, but the three endogenously-calibrated
    # constants (omega, chiH, kappaprob) are model variables, so read their steady state.
    ae = {**aess, **read_params(AE_MODEL)}
    em = {**emss, **read_params(EM_MODEL)}
    pvals = {}
    for _, rows in PARAMETERS:
        for _paper, _desc, code in rows:
            if code in ae:
                a = fmt_val(ae[code])
                e = "--" if code in EMDE_DASH else fmt_val(em[code])
                pvals[code] = (a, e, a != e)  # third element: differs across AE/EMDE
    svals = {}
    for _, rows in ENDOGENOUS:
        for _paper, _desc, code in rows:
            if code in aess:
                svals[code] = (fmt_val(aess[code]), fmt_val(emss[code]))
    # Blue parenthetical notes for the endogenously calibrated parameters.
    CALIB = {
        "omega":     ("labor supply",         "L_t", "L"),
        "kappaprob": ("adoption probability",  "q_t", "q"),
    }
    pnotes = {code: rf"\calibnote{{targets steady-state {label} ${sym}={fmt_val(aess[tgt])}$}}"
              for code, (label, sym, tgt) in CALIB.items()}
    pnotes["chiH"] = r"\calibnote{solved from the steady-state education-time condition}"
    specs = [
        (ENDOGENOUS, "Endogenous Variables", "tab:glossEndo", "glossaryEndogenous.tex", svals, EQNS, None),
        (PARAMETERS, "Parameters",           "tab:glossParam", "glossaryParameters.tex", pvals, None, pnotes),
        (EXOGENOUS,  "Exogenous Variables (Shocks)", "tab:glossExo", "glossaryExogenous.tex", None, None, None),
    ]
    for groups, caption, label, fname, values, eqns, notes in specs:
        (OUT_DIR / fname).write_text(longtable(groups, caption, label, values, eqns, notes), encoding="utf-8")
        nrows = sum(len(rows) for _, rows in groups)
        extra = "" if values is None else " + AE/EMDE values"
        print(f"  Wrote {fname} ({nrows} rows{extra})")


if __name__ == "__main__":
    main()
