"""
Working paper: generate Table 4 (tab:notation), "Main Endogenous Variables".

Writes only the `tabular` environment to ../notationTable.tex; the surrounding
table float, caption, label, source and note stay in draftPaper.tex (same split
as multipliersTable.tex). The notation is fixed by the model, encoded here rather
than computed, so the compiled paper is unchanged when this runs.

Writes (\\input by draftPaper.tex):
  ../notationTable.tex
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "notationTable.tex"            # docs/2026-06_wp-imf/

HEADER = ("% Generated by pyScripts/2026-06_wp-imf/makeNotationTable.py "
          "(run via the docs copy). Do not edit by hand.")

# Two symbol/description column pairs per row.
NOTATION = [
    (r"$C_t$",        "Consumption",               r"$A_t$",          "Adopted technologies"),
    (r"$L_t$",        "Labor supply",              r"$Z_t$",          "Created technologies"),
    (r"$E_t$",        "Time in human capital",     r"$S_t$",          "Adoption expenditure"),
    (r"$N_t$",        r"Effective labor $H_t L_t$", r"$q_t$",         "Adoption probability"),
    (r"$H_t$",        "Private human capital",     r"$\mathcal{V}_t$", "Value of adopted tech."),
    (r"$I_t$",        "Private investment",        r"$\mathcal{J}_t$", "Value of unadopted tech."),
    (r"$K_t$",        "Private capital",           r"$G_t^{C}$",      "Government consumption"),
    (r"$w_t$",        "Real wage",                 r"$I_t^{GI}$",     "Public infrastructure inv."),
    (r"$r_t^{k}$",    "Rental rate of capital",    r"$I_t^{GE}$",     "Public human capital inv."),
    (r"$\lambda_t$",  "Marginal utility",          r"$G_t^{RD}$",     r"Public R\&D spending"),
    (r"$\lambda_t^{H}$", "Shadow value of $H_t$",  r"$K_t^{GI}$",     "Public infrastructure capital"),
    (r"$Y_t^{d}$",    "Aggregate demand",          r"$K_t^{GE}$",     "Public human capital"),
    (r"$Y_t$",        "Gross output",              r"$D_t$",          "Public debt"),
    (r"$mc_t$",       "Real marginal cost",        r"$d_t$",          "Debt-to-GDP ratio"),
    (r"$\Pi_t$",      "Gross inflation",           r"$T_t$",          "Lump-sum transfers"),
    (r"$\Pi_t^{*}$",  "Reset inflation",           r"$\tau_t^{c},\tau_t^{w}$", "Consumption, labor tax"),
    (r"$v_t^{p}$",    "Price dispersion",          r"$R_t^{mp}$",     "Policy rate"),
    (r"$\Lambda_t$",  "Balanced-growth trend",     r"$R_t$",          "Government borrowing rate"),
]


def main():
    lines = [
        HEADER,
        r"\begin{tabular}{ll@{\qquad}ll}",
        r"    \toprule",
        r"    Symbol & Description & Symbol & Description \\",
        r"    \midrule",
    ]
    for s1, d1, s2, d2 in NOTATION:
        lines.append(f"    {s1} & {d1} & {s2} & {d2} \\\\")
    lines += [r"    \bottomrule", r"\end{tabular}"]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  Wrote {OUT.name}")


if __name__ == "__main__":
    main()
