"""
Working paper: generate Table 1 (tab:parameters), "Selected Model Parameters".

Writes only the `tabular` environment to ../parametersTable.tex; the surrounding
table float, caption, label, source and note stay in draftPaper.tex (same split
as multipliersTable.tex).

HYBRID data sourcing. Most rows of Table 1 are *curated* calibration values that
deliberately differ from the raw model parameters and so stay encoded here (see
"why curated" notes per row below). Four parameters map one-for-one onto the
solved model and are read live from the committed _results.mat (AE =
Model_HumanCapital_exp_gc, EMDE = EM_Model_HumanCapital_exp_gc), so a
recalibration of any of them flows into the table automatically:

    alpha_G <- alphaG      (output elasticity, infrastructure)
    rho_A   <- rho_ZZRD    (AR(1) coefficient, technology stock)
    e_GI    <- eGI_ss      (inefficiency, infrastructure investment)
    e_GE    <- eGE_ss      (inefficiency, human capital investment)
    e_GRD   <- eGRD_ss     (inefficiency, public R&D; EMDE shown "--", channel off)
    delta   <- delta/deltaH (depreciation, public capital; the two are equal)
    mu      <- alphaH      (human capital elasticity, public stock)
    gamma   <- muy         (human capital elasticity, time input)

The efficiency gaps e_GI/e_GE equal Table 2's data-derived (EM+LIC)/2 averages for
EMDEs and the AE median for advanced economies, so reading them here keeps Table 1
and Table 2 consistent (and corrects a stale EMDE e_GI value of 0.42 -> 0.41). The
EMDE e_GRD is reported "--" because the R&D channel is shut down there (alphaRD=0),
even though the model still carries eGRD_ss=0.2; the AE e_GRD is the model's 0.41
(slightly above the 0.399 data median, a deliberate calibration choice).

The other rows are kept as literals on purpose. The most important are the
(1-rho_A)-normalized innovation elasticities alpha_HA (0.45 vs code alphaHA=0.10)
and alpha_RD (0.10 vs code alphaRD=0.0189) -- see memory `alphaHA-normalization`;
do NOT "fix" these to the raw params. Others are curated/rounded presentation
values (e.g. survival rate 0.97 vs code phiob=0.98; EMDE adoption elasticity shown
at the AE value rather than the raw EMDE code value; q_0 has no standalone param).

Writes (\\input by draftPaper.tex):
  ../parametersTable.tex
"""
from pathlib import Path

from scipy.io import loadmat

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "parametersTable.tex"          # docs/2026-06_wp-imf/
REPO = HERE.parents[2]                             # repo root
MODELS = REPO / "models"
AE_MODEL = "Model_HumanCapital_exp_gc"
EM_MODEL = "EM_Model_HumanCapital_exp_gc"

HEADER = ("% Generated by pyScripts/2026-06_wp-imf/makeParametersTable.py "
          "(run via the docs copy). Do not edit by hand.")


def read_params(model):
    """Return {param_name: value} from a committed <model>_results.mat."""
    m = loadmat(MODELS / model / "Output" / f"{model}_results.mat")
    M = m["M_"]
    names = [str(x[0]) for x in M["param_names"][0, 0][:, 0]]
    vals = M["params"][0, 0].ravel()
    return dict(zip(names, vals))


def fmt(x, dp):
    return f"{float(x):.{dp}f}"


def build_parameters():
    """(symbol, description, AE value, EMDE value); "--" where a channel is off.

    The four clean parameters are read from the AE/EMDE _results.mat; the rest are
    curated literals (see module docstring for why each is not read from the mat)."""
    ae = read_params(AE_MODEL)
    em = read_params(EM_MODEL)

    # delta and deltaH are the same depreciation rate; verify before showing once.
    assert abs(ae["delta"] - ae["deltaH"]) < 1e-12, "delta != deltaH (AE)"
    assert abs(em["delta"] - em["deltaH"]) < 1e-12, "delta != deltaH (EMDE)"

    return [
        # symbol                       description                                AE                            EMDE
        (r"$\alpha_G$",              "Output elasticity, infrastructure",       fmt(ae["alphaG"], 3),         fmt(em["alphaG"], 2)),      # READ: alphaG (AE 0.054, EMDE 0.17)
        (r"$\alpha_{HA}$",           "Human capital elasticity, innovation",    "0.45",                       "--"),      # curated: (1-rho_A)-normalized vs code 0.10 (alphaHA-normalization)
        (r"$\alpha_{RD}$",           r"Public R\&D elasticity, innovation",     "0.10",                       "--"),      # curated: (1-rho_A)-normalized vs code 0.0189
        (r"$\rho_A$",                "AR(1) coefficient, technology stock",     fmt(ae["rho_ZZRD"], 2),       fmt(em["rho_ZZRD"], 2)),   # READ: rho_ZZRD
        (r"$\phi$",                  "Survival rate of adopted technologies",   "0.97",                       "0.97"),    # curated: vs code phiob=0.98
        (r"$e^{GI}$",                "Inefficiency, infrastructure investment", fmt(ae["eGI_ss"], 2),         fmt(em["eGI_ss"], 2)),     # READ: eGI_ss
        (r"$e^{GE}$",                "Inefficiency, human capital investment",  fmt(ae["eGE_ss"], 2),         fmt(em["eGE_ss"], 2)),     # READ: eGE_ss
        (r"$e^{GRD}$",               r"Inefficiency, public R\&D spending",     fmt(ae["eGRD_ss"], 2),        "--"),      # READ AE: eGRD_ss; EMDE "--" (R&D channel off)
        (r"$\varsigma$",             "Elasticity, adoption probability",        "0.80",                       "0.80"),    # curated: EMDE shown at AE value vs code rhoSADOPT=0.10
        (r"$q_0$",                   "Scale, adoption probability",             "0.10",                       "0.10"),    # curated: not a standalone model param
        (r"$\delta^{GI},\delta^{GE}$", "Depreciation, public capital",          fmt(ae["delta"], 3),          fmt(em["delta"], 3)),      # READ: delta (= deltaH)
        (r"$\mu$",                   "Human capital elasticity, public stock",  fmt(ae["alphaH"], 2),         fmt(em["alphaH"], 2)),     # READ: alphaH
        (r"$\gamma$",                "Human capital elasticity, time input",    fmt(ae["muy"], 2),            fmt(em["muy"], 2)),        # READ: muy
    ]


def main():
    parameters = build_parameters()
    lines = [
        HEADER,
        r"\begin{tabular}{llcc}",
        r"    \toprule",
        r"    & Description & AE & EMDE \\",
        r"    \midrule",
    ]
    for sym, desc, ae, emde in parameters:
        lines.append(f"    {sym} & {desc} & {ae} & {emde} \\\\")
    lines += [r"    \bottomrule", r"\end{tabular}"]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  Wrote {OUT.name}")


if __name__ == "__main__":
    main()
