"""
Working paper: generate Table 1 (tab:parameters), "Selected Model Parameters".

Writes only the `tabular` environment to ../parametersTable.tex; the surrounding
table float, caption, label, source and note stay in draftPaper.tex (same split
as multipliersTable.tex). The values are calibration choices, encoded here rather
than computed, so the compiled paper is unchanged when this runs.

Writes (\\input by draftPaper.tex):
  ../parametersTable.tex
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "parametersTable.tex"          # docs/2026-06_wp-imf/

HEADER = ("% Generated by pyScripts/2026-06_wp-imf/makeParametersTable.py "
          "(run via the docs copy). Do not edit by hand.")

# (symbol, description, AE value, EMDE value); "--" where a channel is off.
PARAMETERS = [
    (r"$\alpha_G$",              "Output elasticity, infrastructure",       "0.05",  "0.17"),
    (r"$\alpha_{HA}$",           "Human capital elasticity, innovation",    "0.45",  "--"),
    (r"$\alpha_{RD}$",           r"Public R\&D elasticity, innovation",     "0.10",  "--"),
    (r"$\rho_A$",                "AR(1) coefficient, technology stock",     "0.79",  "0.79"),
    (r"$\phi$",                  "Survival rate of adopted technologies",   "0.97",  "0.97"),
    (r"$e^{GI}$",                "Inefficiency, infrastructure investment", "0.35",  "0.42"),
    (r"$e^{GE}$",                "Inefficiency, human capital investment",  "0.30",  "0.32"),
    (r"$e^{GRD}$",               r"Inefficiency, public R\&D spending",     "0.41",  "--"),
    (r"$\varsigma$",             "Elasticity, adoption probability",        "0.80",  "0.80"),
    (r"$q_0$",                   "Scale, adoption probability",             "0.10",  "0.10"),
    (r"$\delta^{GI},\delta^{GE}$", "Depreciation, public capital",          "0.025", "0.025"),
    (r"$\mu$",                   "Human capital elasticity, public stock",  "0.10",  "0.25"),
    (r"$\gamma$",                "Human capital elasticity, time input",    "0.50",  "0.50"),
]


def main():
    lines = [
        HEADER,
        r"\begin{tabular}{llcc}",
        r"    \toprule",
        r"    & Description & AE & EMDE \\",
        r"    \midrule",
    ]
    for sym, desc, ae, emde in PARAMETERS:
        lines.append(f"    {sym} & {desc} & {ae} & {emde} \\\\")
    lines += [r"    \bottomrule", r"\end{tabular}"]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  Wrote {OUT.name}")


if __name__ == "__main__":
    main()
