"""
Generate the common macro and policy calibration table for the working paper.

All values are read from the committed AE and EMDE result files. The script
asserts that every displayed parameter is common to the two calibrations.

Writes:
  ../commonParametersTable.tex
"""
from pathlib import Path

from scipy.io import loadmat

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "commonParametersTable.tex"
REPO = HERE.parents[2]
MODELS = REPO / "models"
AE_MODEL = "Model_HumanCapital_exp_gc"
EM_MODEL = "EM_Model_HumanCapital_exp_gc"

HEADER = ("% Generated by pyScripts/2026-06_wp-imf/"
          "makeCommonParametersTable.py. Do not edit by hand.")


def read_params(model):
    m = loadmat(MODELS / model / "Output" / f"{model}_results.mat")["M_"]
    names = [str(x[0]) for x in m["param_names"][0, 0][:, 0]]
    return dict(zip(names, m["params"][0, 0].ravel()))


def fmt(value, decimals):
    return f"{float(value):.{decimals}f}"


def main():
    ae = read_params(AE_MODEL)
    em = read_params(EM_MODEL)

    shown = {
        "betta", "varphi", "alpha", "delta", "deltaH", "thetap", "chi",
        "epsilon", "vartheta", "markupss", "Piss", "rho_R", "gamma_pi",
        "gamma_y", "gamma_d_T",
    }
    for code in shown:
        assert abs(ae[code] - em[code]) < 1e-12, f"{code} differs across calibrations"

    groups = [
        ("Households and capital accumulation", [
            (r"$\beta$", "Discount factor", "betta", 4),
            (r"$\varphi$", "Inverse Frisch elasticity", "varphi", 0),
            (r"$\alpha$", "Private capital share", "alpha", 2),
            (r"$\delta$", "Depreciation rate of physical capital", "delta", 3),
            (r"$\delta^h$", "Depreciation rate of human capital", "deltaH", 3),
        ]),
        ("Price setting and production", [
            (r"$\theta_p$", "Calvo non-reset probability", "thetap", 2),
            (r"$\chi_p$", "Price indexation", "chi", 2),
            (r"$\epsilon$", "Elasticity of substitution across retail goods", "epsilon", 0),
            (r"$\vartheta$", "Love-of-variety exponent", "vartheta", 2),
            (r"$\mu^p$", "Gross markup of intermediate producers", "markupss", 2),
        ]),
        ("Monetary policy and fiscal closure", [
            (r"$\Pi$", "Steady-state gross inflation", "Piss", 2),
            (r"$\rho_R$", "Interest-rate smoothing", "rho_R", 2),
            (r"$\gamma_\pi$", "Policy response to inflation", "gamma_pi", 2),
            (r"$\gamma_y$", "Policy response to aggregate demand", "gamma_y", 2),
            (r"$\gamma_d^T$", "Transfer response to debt", "gamma_d_T", 2),
        ]),
    ]

    lines = [
        HEADER,
        r"\begin{tabular}{llc}",
        r"    \toprule",
        r"    & & Value \\",
        r"    \midrule",
    ]
    for gi, (title, rows) in enumerate(groups):
        if gi:
            lines.append(r"    \addlinespace[0.4em]")
        lines.append(rf"    \multicolumn{{3}}{{@{{}}l}}{{\textit{{{title}}}}} \\")
        lines.append(r"    \addlinespace[0.1em]")
        for symbol, description, code, decimals in rows:
            lines.append(
                rf"    \quad {symbol} & {description} & {fmt(ae[code], decimals)} \\"
            )
    lines += [r"    \bottomrule", r"\end{tabular}"]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  Wrote {OUT.name}")


if __name__ == "__main__":
    main()
