"""
Working paper: generate the structural-channel parameter table (tab:parameters).

Writes only the `tabular` environment to ../parametersTable.tex; the surrounding
table float, caption, label, source and note stay in draftPaper.tex (same split
as multipliersTable.tex).

Every displayed value maps one-for-one onto the solved model and is read live
from the committed _results.mat (AE = Model_HumanCapital_exp_gc, EMDE =
EM_Model_HumanCapital_exp_gc), so a recalibration flows into the table
automatically:

    alpha_G <- alphaG      (output elasticity, infrastructure)
    rho_A   <- rho_A         (AR(1) coefficient, technology stock)
    alpha_HA <- alphaHA    (long-run HC elasticity; EMDE "--", channel off)
    alpha_RD <- alphaRD    (long-run R&D elasticity; EMDE "--", channel off)
    varsigma <- varsigma  (adoption-probability elasticity, AE; EMDE "--", dormant)
    phi     <- phi               (survival rate of adopted technologies, 1 - 0.08/4)
    mu      <- mu              (human capital elasticity, public stock)
    gamma   <- gamma              (human capital elasticity, time input)

alpha_HA and alpha_RD are shown as their explicit long-run elasticities. The
technology-creation equation multiplies them by (1-rho_A), giving per-quarter
loadings of 0.10 and 0.0189 at the AE calibration.

varsigma (adoption-probability elasticity) reads the AE varsigma and is "--" for
EMDEs: their endogenous innovation channel is off, so the spending-driven adoption
response is dormant (verified: the adoption block does not move in EMDE
experiments), exactly as for alpha_HA/alpha_RD.

The paper's adoption-probability scale q_0 is intentionally not a row here.
The code represents it with the endogenous object `kappaprob`, which is solved
in steady state to hit the targeted adoption probability
probadoptss=0.2/4=0.05. It is therefore discussed with the internally calibrated
scales in draftPaper.tex rather than tabulated as a structural parameter.

Every row in this table is now read from _results.mat or is a documented "--".

Writes (\\input by draftPaper.tex):
  ../parametersTable.tex
"""
from pathlib import Path

from scipy.io import loadmat

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "parametersTable.tex"          # docs/2026-06_wp-imf/
REPO = HERE.parents[2]                             # repo root
MODELS = REPO / "models"
AE_MODEL = "Model_HumanCapital_exp_gc"
EM_MODEL = "EM_Model_HumanCapital_exp_gc"

HEADER = ("% Generated by pyScripts/2026-06_wp-imf/makeParametersTable.py "
          "(run via the docs copy). Do not edit by hand.")


def read_params(model):
    """Return {param_name: value} from a committed <model>_results.mat."""
    m = loadmat(MODELS / model / "Output" / f"{model}_results.mat")
    M = m["M_"]
    names = [str(x[0]) for x in M["param_names"][0, 0][:, 0]]
    vals = M["params"][0, 0].ravel()
    return dict(zip(names, vals))


def fmt(x, dp):
    return f"{float(x):.{dp}f}"


def build_groups():
    """Return [(group title, [(symbol, description, AE, EMDE), ...]), ...].

    Parameters are grouped by the productive-spending channel they govern. Every
    value is read from the
    AE/EMDE _results.mat or is a documented "--" (innovation channel off for EMDEs);
    see the module docstring for the param mapping and the q_0 omission."""
    ae = read_params(AE_MODEL)
    em = read_params(EM_MODEL)

    return [
        ("Public infrastructure", [
            (r"$\alpha_G$",                "Output elasticity of public infrastructure", fmt(ae["alphaG"], 3), fmt(em["alphaG"], 2)),
        ]),
        ("Human capital accumulation", [
            (r"$\mu$",     "Elasticity w.r.t.\\ the public human-capital stock", fmt(ae["mu"], 2), fmt(em["mu"], 2)),
            (r"$\gamma$",  "Elasticity w.r.t.\\ the time input",                 fmt(ae["gamma"], 2),    fmt(em["gamma"], 2)),
        ]),
        ("Technology creation and adoption", [
            (r"$\alpha_{HA}$", "Long-run human-capital elasticity",       fmt(ae["alphaHA"], 2),    "--"),
            (r"$\alpha_{RD}$", r"Long-run public-R\&D elasticity",        fmt(ae["alphaRD"], 2),    "--"),
            (r"$\rho_A$",      "Persistence of created technology",       fmt(ae["rho_A"], 2),   fmt(em["rho_A"], 2)),
            (r"$\phi$",        "Survival rate of adopted technologies",   fmt(ae["phi"], 2),      fmt(em["phi"], 2)),
            (r"$\varsigma$",   "Elasticity of the adoption probability",  fmt(ae["varsigma"], 2),  "--"),
        ]),
    ]


def main():
    groups = build_groups()
    lines = [
        HEADER,
        r"\begin{tabular}{llcc}",
        r"    \toprule",
        r"    & & AE & EMDE \\",
        r"    \midrule",
    ]
    for gi, (title, rows) in enumerate(groups):
        if gi > 0:
            lines.append(r"    \addlinespace[0.4em]")
        lines.append(rf"    \multicolumn{{4}}{{@{{}}l}}{{\textit{{{title}}}}} \\")
        lines.append(r"    \addlinespace[0.1em]")
        for sym, desc, ae, emde in rows:
            lines.append(rf"    \quad {sym} & {desc} & {ae} & {emde} \\")
    lines += [r"    \bottomrule", r"\end{tabular}"]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  Wrote {OUT.name}")


if __name__ == "__main__":
    main()
