"""
Generate the appendix tables that map OECD government investment by function
into the model's infrastructure and human-capital-related investment blocks.

Source: Table J.10.4 in data/ocz3gw.xlsx (OECD, Government at a Glance 2025).
Country groups follow the April 2025 IMF World Economic Outlook classification.
The OECD and OECD-EU aggregate rows are excluded; every country receives equal
weight in the reported group means and medians.

Writes:
  ../investmentFunctionMappingTable.tex
  ../investmentCompositionTable.tex
  ../csvFiles/investmentCompositionByCountry.csv
  ../csvFiles/investmentCompositionAggregates.csv
"""
from csv import DictWriter
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
from statistics import mean, median

import openpyxl

HERE = Path(__file__).resolve().parent
DOCS = HERE.parent
REPO = HERE.parents[2]
DATA = REPO / "data" / "ocz3gw.xlsx"
MAPPING_TEX = DOCS / "investmentFunctionMappingTable.tex"
AGGREGATES_TEX = DOCS / "investmentCompositionTable.tex"
COUNTRY_CSV = DOCS / "csvFiles" / "investmentCompositionByCountry.csv"
AGGREGATES_CSV = DOCS / "csvFiles" / "investmentCompositionAggregates.csv"

INFRASTRUCTURE = [
    "General public services",
    "Defence",
    "Public order and safety",
    "Economic affairs",
    "Environmental protection",
]

HUMAN_CAPITAL = [
    "Housing and community amenities",
    "Health",
    "Recreation, culture and religion",
    "Education",
    "Social protection",
]

ADVANCED_ECONOMIES = {
    "Austria", "Belgium", "Croatia", "Czechia", "Denmark", "Estonia",
    "Finland", "France", "Germany", "Greece", "Iceland", "Ireland",
    "Israel", "Italy", "Japan", "Korea", "Latvia", "Lithuania",
    "Luxembourg", "Netherlands", "Norway", "Portugal", "Slovak Republic",
    "Slovenia", "Spain", "Sweden", "Switzerland", "United Kingdom",
    "United States",
}

EMDES = {
    "Bulgaria", "Chile", "Colombia", "Costa Rica", "Hungary", "Poland",
    "Romania",
}

HEADER = "% Generated by pyScripts/makeInvestmentCompositionTables.py. Do not edit by hand."


def f2(value):
    """Format to two decimals using conventional half-up rounding."""
    return str(Decimal(str(value)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP))


def read_country_data():
    workbook = openpyxl.load_workbook(DATA, data_only=True, read_only=True)
    sheet = workbook["tj10-4"]
    headers = [sheet.cell(3, col).value for col in range(3, 13)]
    expected = INFRASTRUCTURE + HUMAN_CAPITAL
    if headers != expected:
        raise ValueError(f"Unexpected Table J.10.4 columns: {headers}")

    records = []
    for row in sheet.iter_rows(min_row=4, max_row=41, min_col=2, max_col=12,
                               values_only=True):
        country, *values = row
        if country in {"OECD", "OECD-EU"}:
            continue
        group = "AE" if country in ADVANCED_ECONOMIES else "EMDE" if country in EMDES else None
        if group is None:
            raise ValueError(f"Country is not assigned to AE or EMDE: {country}")

        by_function = dict(zip(headers, map(float, values)))
        total = sum(by_function.values())
        if abs(total - 100) > 0.01:
            raise ValueError(f"Functional shares for {country} sum to {total:.4f}, not 100")

        infrastructure = sum(by_function[name] for name in INFRASTRUCTURE)
        human_capital = sum(by_function[name] for name in HUMAN_CAPITAL)
        records.append({
            "country": country,
            "group": group,
            **by_function,
            "infrastructure_and_other_public_capital": infrastructure,
            "human_capital_related": human_capital,
        })

    expected_countries = ADVANCED_ECONOMIES | EMDES
    observed_countries = {record["country"] for record in records}
    if observed_countries != expected_countries:
        raise ValueError(
            f"Country coverage changed; missing={expected_countries-observed_countries}, "
            f"extra={observed_countries-expected_countries}"
        )
    return records


def aggregate(records):
    output = []
    for code, label in (("AE", "Advanced economies"), ("EMDE", "EMDEs")):
        group = [record for record in records if record["group"] == code]
        infrastructure = [record["infrastructure_and_other_public_capital"] for record in group]
        human_capital = [record["human_capital_related"] for record in group]
        for statistic, function in (("Unweighted mean", mean), ("Median", median)):
            output.append({
                "group": code,
                "group_label": label,
                "statistic": statistic,
                "economies": len(group),
                "infrastructure_and_other_public_capital": function(infrastructure),
                "human_capital_related": function(human_capital),
            })
    return output


def write_csvs(records, aggregates):
    COUNTRY_CSV.parent.mkdir(parents=True, exist_ok=True)
    country_fields = [
        "country", "group", *INFRASTRUCTURE, *HUMAN_CAPITAL,
        "infrastructure_and_other_public_capital", "human_capital_related",
    ]
    with COUNTRY_CSV.open("w", encoding="utf-8", newline="") as file:
        writer = DictWriter(file, fieldnames=country_fields, lineterminator="\n")
        writer.writeheader()
        writer.writerows(records)

    aggregate_fields = [
        "group", "group_label", "statistic", "economies",
        "infrastructure_and_other_public_capital", "human_capital_related",
    ]
    with AGGREGATES_CSV.open("w", encoding="utf-8", newline="") as file:
        writer = DictWriter(file, fieldnames=aggregate_fields, lineterminator="\n")
        writer.writeheader()
        writer.writerows(aggregates)


def write_mapping_table():
    lines = [
        HEADER,
        r"\begin{tabularx}{\textwidth}{@{}>{\raggedright\arraybackslash}p{0.34\textwidth}X@{}}",
        r"    \toprule",
        r"    Model investment block & OECD functional categories \\",
        r"    \midrule",
        (r"    Infrastructure and other public capital ($I^{GI}$) & General public services; defence; "
         r"public order and safety; economic affairs; environmental protection. \\"),
        r"    \addlinespace[0.3em]",
        (r"    Human-capital-related investment ($I^{GE}$) & Housing and community amenities; health; "
         r"recreation, culture and religion; education; social protection. \\"),
        r"    \bottomrule",
        r"\end{tabularx}",
    ]
    MAPPING_TEX.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_aggregate_table(aggregates):
    lines = [
        HEADER,
        r"\begin{tabular}{lccc}",
        r"    \toprule",
        r"    Country-group statistic & Economies & Infrastructure ($s^{GI}$) & Human capital ($s^{GE}$) \\",
        r"    \midrule",
    ]
    for index, row in enumerate(aggregates):
        if index == 2:
            lines.append(r"    \addlinespace[0.3em]")
        label = f"{row['group_label']}: {row['statistic'].lower()}"
        lines.append(
            f"    {label} & {row['economies']} & "
            f"{f2(row['infrastructure_and_other_public_capital'])} & "
            f"{f2(row['human_capital_related'])} \\\\"
        )
    lines += [r"    \bottomrule", r"\end{tabular}"]
    AGGREGATES_TEX.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    records = read_country_data()
    aggregates = aggregate(records)
    write_csvs(records, aggregates)
    write_mapping_table()
    write_aggregate_table(aggregates)
    for path in (COUNTRY_CSV, AGGREGATES_CSV, MAPPING_TEX, AGGREGATES_TEX):
        print(f"  Wrote {path.relative_to(REPO)}")


if __name__ == "__main__":
    main()
