"""
Generate LaTeX macros with the 2023 efficiency gaps for the calibration-table
slide, read from the bands chart's own data file (efficiencyBandsJAM.csv) so the
table stays aligned with Figure 5 and updates when the estimates change.

  Advanced  = the advanced-economy 2023 median
  EMDE      = average of the emerging-market and low-income 2023 medians
  Jamaica   = its 2023 value
  Human capital = average of health and education

Writes ../latex/calibrationValues.tex (\\input by presentation.tex). Re-run
after regenerating the chart: python3 makeCalibrationValues.py
"""
from pathlib import Path
import pandas as pd

HERE = Path(__file__).resolve().parent
CSV = HERE.parent / "latex" / "figures" / "efficiencyBandsJAM.csv"
OUT = HERE.parent / "latex" / "calibrationValues.tex"
YEAR = 2023
SECTORS = ["INF", "HLT", "EDU"]


def main():
    d = pd.read_csv(CSV)
    d = d[d["year"] == YEAR]

    def p50(series, sector):
        return float(d[(d["series"] == series) & (d["sector"] == sector)]["p50"].iloc[0])

    ae = {s: p50("Advanced economies", s) for s in SECTORS}
    em = {s: p50("Emerging markets", s) for s in SECTORS}
    li = {s: p50("Low-income", s) for s in SECTORS}
    jam = {s: p50("Jamaica", s) for s in SECTORS}
    # EMDE = average of the emerging-market and low-income medians (rounded to
    # 3dp first so the printed "(a+b)/2 = c" is internally consistent).
    r3 = lambda x: round(x, 3)
    emde = {s: (r3(em[s]) + r3(li[s])) / 2 for s in SECTORS}

    hc = lambda v: (v["HLT"] + v["EDU"]) / 2

    macros = {
        "calAeInf": ae["INF"], "calAeHlt": ae["HLT"], "calAeEdu": ae["EDU"], "calAeHC": hc(ae),
        "calEmInf": em["INF"], "calEmHlt": em["HLT"], "calEmEdu": em["EDU"],
        "calLiInf": li["INF"], "calLiHlt": li["HLT"], "calLiEdu": li["EDU"],
        "calEmdeInf": emde["INF"], "calEmdeHlt": emde["HLT"], "calEmdeEdu": emde["EDU"],
        "calEmdeHC": (r3(emde["HLT"]) + r3(emde["EDU"])) / 2,
        "calJamInf": jam["INF"], "calJamHlt": jam["HLT"], "calJamEdu": jam["EDU"], "calJamHC": hc(jam),
    }

    lines = [
        "% Auto-generated by pyScripts/makeCalibrationValues.py from",
        "% latex/figures/efficiencyBandsJAM.csv (2023 medians). Do not edit by hand.",
        "",
    ]
    lines += [f"\\newcommand{{\\{k}}}{{{v:.3f}}}" for k, v in macros.items()]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"  Wrote {OUT.name}")
    for k, v in macros.items():
        print(f"    {k} = {v:.3f}")


if __name__ == "__main__":
    main()
