"""
Jamaica case deck: fiscal-multiplier table.

The model's post-simulation block (models/postSimul.mod) computes cumulative
output multipliers at 1/5/10/20/25-year horizons but only *prints* them; they
are never written to the _results.mat or the exported CSVs. This script
reproduces that calculation exactly from the committed simulation paths and
persists the result, so the deck has a reproducible, linked source.

For each scenario it loads <model>/Output/<model>_results.mat, takes the
endogenous simulation oo_.endo_simul (column 1 = pre-shock steady state), and
applies the postSimul.mod formula

    fiscalchange = (Ig-Igss) + (Ige-Igess) + (Cgrd-Cgrdss)
    multiplier_Ny = sum(yd(2:N*4+1) - yd(1)) / sum(fiscalchange(2:N*4+1))

i.e. the cumulative output gain over the cumulative fiscal injection. Period 1
(endo_simul column 1) is the pre-shock steady state and is excluded; the shock
is active from period 2, so an N-year horizon spans the 4N quarters in indices
2:(N*4+1). The experiments are the pure
1%-of-GDP permanent spending shocks: infrastructure (epsi_ig) and human-capital
(epsi_ige) spending, for the advanced, EMDE and Jamaica calibrations.

Writes:
  ../csvFiles/multipliers.csv      (one row per scenario, all horizons)
  ../latex/multipliersTable.tex    (\\input by presentation.tex)
"""
from pathlib import Path
import numpy as np
from scipy.io import loadmat

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]                       # .../2025-05_spendingModelling
MODELS = REPO / "models"
CSV_OUT = HERE.parent / "csvFiles" / "multipliers.csv"
TEX_OUT = HERE.parent / "latex" / "multipliersTable.tex"

HORIZONS = [1, 5, 10, 20, 25]                # years; quarter window is N*4

# (spending-type label, region label, model directory)
SCENARIOS = [
    ("Infrastructure investment", "Advanced", "Model_HumanCapital_epsi_ig"),
    ("Infrastructure investment", "EMDEs",    "EM_Model_HumanCapital_epsiig"),
    ("Infrastructure investment", "Jamaica",  "JAM_Model_HumanCapital_epsiig"),
    ("Human capital",             "Advanced", "Model_HumanCapital_epsi_cge"),
    ("Human capital",             "EMDEs",    "EM_Model_HumanCapital_epsicge"),
    ("Human capital",             "Jamaica",  "JAM_Model_HumanCapital_epsicge"),
]


def multipliers(model):
    """Cumulative output multipliers at each horizon, per postSimul.mod."""
    m = loadmat(MODELS / model / "Output" / f"{model}_results.mat")
    oo, M = m["oo_"], m["M_"]
    sim = oo["endo_simul"][0, 0]                       # n_endo x T
    names = [str(x[0]) for x in M["endo_names"][0, 0][:, 0]]
    idx = {n: i for i, n in enumerate(names)}
    ss = oo["steady_state"][0, 0].ravel()

    yd = sim[idx["yd"]]
    fc = ((sim[idx["Ig"]] - ss[idx["Ig"]])
          + (sim[idx["Ige"]] - ss[idx["Ige"]])
          + (sim[idx["Cgrd"]] - ss[idx["Cgrd"]]))
    out = {}
    for h in HORIZONS:
        ped = h * 4 + 1                                # MATLAB yd(2:ped); period 1 = SS, excluded
        out[h] = float(np.sum(yd[1:ped] - yd[0]) / np.sum(fc[1:ped]))
    return out


def main():
    rows = []
    for stype, region, model in SCENARIOS:
        mult = multipliers(model)
        rows.append((stype, region, model, mult))
        vals = "  ".join(f"{h}y={mult[h]:.2f}" for h in HORIZONS)
        print(f"  {region:9s} {stype:26s} {vals}")

    # CSV record
    CSV_OUT.parent.mkdir(parents=True, exist_ok=True)
    with CSV_OUT.open("w", encoding="utf-8") as f:
        f.write("spending,region,model," + ",".join(f"mult_{h}y" for h in HORIZONS) + "\n")
        for stype, region, model, mult in rows:
            f.write(f"{stype},{region},{model}," +
                    ",".join(f"{mult[h]:.4f}" for h in HORIZONS) + "\n")
    print(f"  Wrote {CSV_OUT.name}")

    # LaTeX table fragment
    def fmt(v):
        return f"{v:.2f}"

    def datarow(region, mult):
        return ("\\quad " + region + " & "
                + " & ".join(fmt(mult[h]) for h in HORIZONS) + " \\\\")

    lines = [
        "% Generated by pyScripts/makeMultipliers.py from the committed",
        "% _results.mat simulation paths (postSimul.mod formula). Do not edit by hand.",
        "\\begin{tabular}{l c c c c c}",
        "    \\toprule",
        "    Cumulative output multiplier & 1y & 5y & 10y & 20y & 25y \\\\",
        "    \\midrule",
    ]
    last_type = None
    for stype, region, model, mult in rows:
        if stype != last_type:
            if last_type is not None:
                lines.append("    \\addlinespace[0.2em]")
            lines.append(f"    \\multicolumn{{6}}{{l}}{{\\textit{{{stype}}}}} \\\\")
            last_type = stype
        lines.append("    " + datarow(region, mult))
    lines += ["    \\bottomrule", "\\end{tabular}"]
    TEX_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  Wrote {TEX_OUT.name}")


if __name__ == "__main__":
    main()
