mv ./models/Model_HumanCapital_epsiig/Output/Model_HumanCapital_epsiig_results.mat ./models/Model_HumanCapital_epsi_ig/Output/Model_HumanCapital_epsi_ig_results.mat
mv ./models/+Model_HumanCapital_epsiig ./models/+Model_HumanCapital_epsi_ig
mv ./models/Model_HumanCapital_epsiig.log ./models/Model_HumanCapital_epsi_ig.log
mv ./models/Model_HumanCapital_epsicg/Output/Model_HumanCapital_epsicg_results.mat ./models/Model_HumanCapital_epsi_cge/Output/Model_HumanCapital_epsi_cge_results.mat
mv ./models/+Model_HumanCapital_epsicg ./models/+Model_HumanCapital_epsi_cge
mv ./models/Model_HumanCapital_epsicg.log ./models/Model_HumanCapital_epsi_cge.log
mv ./models/+Model_HumanCapital_epsigrd ./models/+Model_HumanCapital_epsi_cgrd
mv ./models/Model_HumanCapital_epsigrd/Output/Model_HumanCapital_epsigrd_results.mat ./models/Model_HumanCapital_epsi_cgrd/Output/Model_HumanCapital_epsi_cgrd_results.mat
mv ./models/Model_HumanCapital_epsigrd.log ./models/Model_HumanCapital_epsi_cgrd.log
mv ./models/Model_HumanCapital_epsiall.log ./models/Model_HumanCapital_epsi_all.log
mv ./models/+Model_HumanCapital_epsiall ./models/+Model_HumanCapital_epsi_all
mv ./models/Model_HumanCapital_epsiall/Output/Model_HumanCapital_epsiall_results.mat ./models/Model_HumanCapital_epsi_all/Output/Model_HumanCapital_epsi_all_results.mat