%% preamble
clear all; close all; clc;
utils.call.paths;

envi = environment.setup();

cd(fullfile(project_path, 'models'));

%% ----------------
% Configuration
% ----------------
% Across-variables contribution decomposition: a SINGLE shock model, with one
% panel per target variable. This is the complement of plotContributions.m,
% which fixes the variable (yd) and varies the model. Each target variable's
% equation must carry a [name='...'] tag in models/model_block.modpart (and the
% models re-solved) for utils.subroutines.createContributions to find it; add
% more variables to aItemList once their equations are tagged.
aModel = "Model_HumanCapital_epsi_ig";   % infrastructure-investment shock
aItemList = ["yd"];                       % target variables (one panel each)

%% ----------------
% Loading the database
% ----------------
resultsRaw = load(fullfile(project_path, 'models', char(aModel), 'Output', [char(aModel) '_results.mat']));
dataRange = qq(0, 4): qq(0, 4) + size(resultsRaw.oo_.endo_simul', 1) - 1;

endo = databank.fromArray(resultsRaw.oo_.endo_simul', resultsRaw.M_.endo_names, dataRange(1));
ss   = databank.fromArray(repmat(resultsRaw.oo_.steady_state', numel(dataRange), 1), resultsRaw.M_.endo_names, dataRange(1));

%% calculating the contributions
contributionSeries = struct();
allItemList = aItemList;
for aItem = aItemList
    [ ...
        contributionSeries.total.(aItem) ...
        , contributionSeries.contrib.(aItem) ...
        , contributionSeries.lhs.(aItem) ...
        ] = utils.subroutines.createContributions( ...
            resultsRaw.M_ ...
            , char(aItem) ...
            , utils.subroutines.Series2Dseries(endo) ...
            , utils.subroutines.Series2Dseries(ss) ...
        );
    allItemList = [allItemList, contributionSeries.contrib.(aItem).Comment];
end
allItemList = unique(allItemList);

% One colour per contributing item, shared across all panels.
colorTable = table( ...
    'Size', [numel(allItemList), 1] ...
    , 'VariableTypes', {'cell'} ...
    , 'VariableNames', {'colorIndex'} ...
    , 'RowNames', allItemList ...
    );
colormapSaved = utils.subroutines.linspecer(numel(allItemList));
for aItemIndex = 1:numel(allItemList)
    colorTable{aItemIndex, 1} = {colormapSaved(aItemIndex, :)};
end
contributionSeries.colorTable = colorTable;

%% plotting one panel per target variable
panelContributionsByVariable(aModel, aItemList, contributionSeries, project_path);

%%
function panelContributionsByVariable(aModel, VarListToPlot, contributionSeries, projectPath)

    VarListToPlot = string(VarListToPlot);

    % Date range
    DateRange = qq(1,1):qq(25,4);
    DateRangeDateTime = dater.toMatlab(DateRange);

    % Adaptive tiled layout: one panel per target variable, near-square grid.
    nVars = numel(VarListToPlot);
    nCols = ceil(sqrt(nVars));
    nRows = ceil(nVars / nCols);

    figure
    t = tiledlayout(nRows, nCols, 'TileSpacing', 'compact', 'Padding', 'compact');
    h = gcf;
    set(h, 'Units', 'centimeters', 'Position', [0 0 21-2*2.5 20-2*2.5])
    set(h, 'defaulttextinterpreter', 'latex');

    for aItem = VarListToPlot % one panel per variable
        nexttile;
        grid on
        hold on

        title( ...
            sprintf('Decomposition of %s', contributionSeries.lhs.(aItem)) ...
            , 'Fontsize', 7 ...
            , 'Fontweight', 'normal' ...
            );

        % stacked contributions
        bars_ = barcon( ...
            DateRange ...
            , contributionSeries.contrib.(aItem) ...
            , "ColorMap", cell2mat(contributionSeries.colorTable{contributionSeries.contrib.(aItem).Comment, :}) ...
            , 'EdgeColor', 'none');
        % target (total) line
        line_ = plot( ...
            DateRange ...
            , contributionSeries.total.(aItem) ...
            , 'color', cell2mat(contributionSeries.colorTable{aItem, :}) ...
            , 'linewidth', 2 ...
            , 'Marker', '_' ...
            , 'MarkerFaceColor', utils.subroutines.rgb('black') ...
            , 'MarkerEdgeColor', utils.subroutines.rgb('black') ...
            , 'MarkerSize', 4 ...
            );

        hold off

        xtickformat(gca, 'yyQQQ')
        set(gca ...
            , 'Xtick', DateRangeDateTime(1:40:end) ...
            , 'Fontsize', 7 ...
            , 'Box', 'off' ...
            , 'TickLabelInterpreter', 'latex' ...
            );

        legendLabels = replace([contributionSeries.contrib.(aItem).Comment, aItem], "_", "\_");
        legend( ...
            [bars_, line_] ...
            , legendLabels ...
            , 'location', 'northoutside' ...
            , 'Interpreter', 'latex' ...
            , 'Fontsize', 6 ...
            , 'NumColumns', 2 ...
            );
    end

    % Save graph
    chartsDir = fullfile(projectPath, 'docs', 'contributions');
    if ~exist(chartsDir, 'dir'); mkdir(chartsDir); end
    fileName = fullfile(chartsDir, "contribByVariable_" + aModel);
    exportgraphics(t, sprintf('%s.png', fileName), 'BackgroundColor', 'none');
    fprintf('Graph saved as: %s.png\n', fileName);
end
